title: Stack Problems
description: My Personal Stack Problems
author: Tran Hong Quan
github: https://github.com/hongquan95
about: Da Nang, VN, 2019.
# google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "http://facebook.com/100003224411093"
    - icon: fa-github
      link: "https://github.com/hongquan95"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    # - text: About Me
    #   url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://hongquan95.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
